global:
  scrape_interval:     1m
  evaluation_interval: 1m

  external_labels:
      monitor: 'prometheus-grafana-exporter'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "prometheus_alert_rules/*.rules"

scrape_configs:

#  - job_name: 'node-exporter'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['nodeexporter:9100']
#        labels:
#           group: 'host'





  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']



  - job_name: 'blackbox'
    scrape_interval: 1m
    scrape_timeout: 15s 
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: ['/etc/prometheus/blackbox_targets.yml']
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox_exporter:9115
